### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [Charptr0/SimpleTweets#2]
The following feature is checked in the readme but **not shown in the GIF**. This user story is not given points. Please record a new GIF and resubmit your assignment using the submit button in the course portal in order to get full points for the user story.

- User is displayed the relative **timestamp for each tweet** ""8m"", ""7h""

In order for us to count these towards your submission, please record another GIF that captures these features. Once you do, please push your updates and **submit your assignment again through the course portal within 48 hours from the posted deadline so that we can regrade it**.

**Comment by Charptr0** [comment]
Hello, I have implemented the timestamp feature

Please check the GIF now 👍
